name: Continuous Integration

# This workflow is triggered on pull requests to the main branch
on:
  pull_request:
    branches: [ main ]

jobs:
  cache-dependencies:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache Node.js modules
        uses: actions/cache@v2
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

  lint:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run linting
        run: npm run lint

  test:
    needs: cache-dependencies
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Run tests
        run: npm run test

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build project
        run: npm run build

  # label-pull-request:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Label Pull Request
  #       uses: pascalgn/size-label-action@1.0.0
  #       with:
  #         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
